on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  
  build_manually:
    if: github.ref == 'refs/heads/next_release' && github.event_name != 'push'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
