on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  
  build_manually:
    if: github.ref != 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
